version: '2'

networks:
  dev_net:
    external: true

services:
  monitoring:
    container_name: blockchain-monitoring
    image: blockchainmonitoring/blockchain-monitoring:latest
    volumes:
      - $FABRIC_NET_CONFIG:/etc/conf/net-config.yaml
#      if you want customize configuration grafana or influxdb
#      - ./influxdb.conf:/etc/influxdb/influxdb.conf
#      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
#     SCHEDULED_TASKS_DELAY - defaule is 1000 milliseconds
      SCHEDULED_TASKS_DELAY: 1000000
    ports:
      - "3000:3000"
      - "8086:8086"
    networks:
      dev_net:
        ipv4_address: 172.25.0.135
